language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install  --prefer-source --no-interaction --dev
